# Generated by Django 3.2.9 on 2021-11-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stuid',
        ),
    ]
