# Generated by Django 3.2.9 on 2021-11-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_remove_student_stuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stuemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stupass',
            new_name='password',
        ),
    ]
