# Generated by Django 3.2.9 on 2021-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admit_date',
            field=models.DateTimeField(default='2021-01-01 10:00:00'),
        ),
    ]
