# Generated by Django 3.2.9 on 2021-12-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counstruction',
            new_name='Construction',
        ),
    ]
