# Generated by Django 3.2.9 on 2021-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=70)),
                ('stuemail', models.CharField(max_length=70)),
                ('stupass', models.CharField(max_length=40)),
            ],
        ),
    ]
