# Generated by Django 3.2.9 on 2021-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(default='Not Available', max_length=40),
        ),
    ]
